# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :local do
    date = Time.new.strftime("%m%d%H%M")
    dir="#{date}"
    puts("*************| 打包项目到目录 |*************")
        build_ios_app(
                workspace: "Knight.xcworkspace",
                scheme: "Knight",
                xcargs: "-allowProvisioningUpdates",
		output_name:"#{date}",
                silent: false,
                include_bitcode: false,
                clean:true,
                configuration:"Release",
                export_method:"app-store",
                buildlog_path: "#{dir}",
                output_directory:"#{dir}",
	)
        puts("\n*************| 打包完成 |*************\n")
        puts('output_directory: "#{dir}"')
    upload_to_testflight(skip_submission: true,
                         skip_waiting_for_build_processing: true)
  end
end
